import { describe, expect, test } from "bun:test";
import { randomUUID } from "node:crypto";
import fixture from "./fixtures/native-history-v1.json";
import { parseFeedBlock, parseStatus } from "./wire";
import { SimulatorStorage } from "./storage";
import { openDb } from "../db";

// Generated by the Rust redb-backed unsigned producer. Small independent cross-language golden.
test("Rust-produced metadata fixture validates canonical headers, feed digests and outcomes", () => {
  expect(parseStatus(fixture.status).head.height).toBe("2");
  for (const raw of fixture.blocks) {
    const b = parseFeedBlock(raw);
    expect(b.feedDigest).toBe(raw.feedDigest);
    expect(b.header.hash).toBe(raw.header.hash);
  }
  expect(() =>
    parseFeedBlock({
      ...fixture.blocks[2],
      feedDigest: fixture.blocks[1]!.feedDigest,
    }),
  ).toThrow("InvalidFeedDigest");
});

import { oracleHistory } from "./testOracle";
const longFixture = process.env.TEST_SIMULATOR_FIXTURE;
describe.skipIf(!process.env.TEST_DATABASE_URL || !longFixture)(
  "real Rust/PostgreSQL independent lifecycle oracle",
  () => {
    test("all retained Eq pages and namespaces match logical oracle across reopen/replay", async () => {
      const f = await Bun.file(longFixture!).json(),
        status = parseStatus(f.status),
        blocks = f.blocks as unknown[];
      if (
        status.workload.extraRowsPerBlock !== 0 ||
        status.workload.version !== 1
      )
        throw Error("oracle requires base workload v1");
      const url = process.env.TEST_DATABASE_URL!,
        schema = "sim_cross_" + randomUUID().replaceAll("-", "");
      const s = await SimulatorStorage.open(url, status, schema);
      let reopened: SimulatorStorage | undefined;
      try {
        for (const block of blocks) await s.ingest(block);
        reopened = await SimulatorStorage.open(url, status, schema);
        for (const oracle of oracleHistory(
          Number(status.head.height),
          status.workload.seed,
          status.workload.payloadBytes,
        )) {
          const page = await reopened.page("namespaces", {
            atHeight: oracle.height,
          });
          expect(page.rows).toEqual(oracle.namespaces);
          for (const [namespaceId, rows] of oracle.records) {
            expect(
              (
                await reopened.page("records", {
                  namespaceId,
                  atHeight: oracle.height,
                })
              ).rows,
            ).toEqual(rows);
            for (const [type, value] of [
              ["u64", "1"],
              ["u64", "2"],
              ["str", "1"],
            ] as const)
              for (const limit of [1, 3, 64]) {
                const expected = rows.filter((r) =>
                    r.attributes.some(
                      (a) =>
                        a.name === "group" &&
                        a.type === type &&
                        a.value === value,
                    ),
                  ),
                  found: unknown[] = [];
                let cursor: string | null = null;
                do {
                  const result = await reopened.page("records", {
                    namespaceId,
                    atHeight: oracle.height,
                    limit,
                    predicate: {
                      op: "eq",
                      attribute: { name: "group", type, value },
                    },
                    ...(cursor ? { cursor } : {}),
                  });
                  expect(result.snapshot.height).toBe(oracle.height);
                  found.push(...result.rows);
                  cursor = result.nextCursor;
                } while (cursor);
                expect(found).toEqual(expected);
              }
            expect(
              (
                await reopened.page("raw", {
                  namespaceId,
                  atHeight: oracle.height,
                })
              ).rows,
            ).toEqual([]);
          }
        }
        for (const b of blocks)
          expect(await reopened.ingest(b)).toBe("duplicate");
        expect((await s.progress()).blocks).toBe(String(blocks.length));
      } finally {
        await reopened?.close();
        await s.close();
        const db = openDb(url);
        try {
          await db.query(`DROP SCHEMA "${schema}" CASCADE`);
        } finally {
          await db.close();
        }
      }
    }, 30000);
  },
);
